INSERT INTO user_account (
    com_id,
    company_code,
    employee_id,
    login_id,
    email,
    password,
    name,
    role,
    status,
    is_deleted
) VALUES
      (
          1,
          'COMP001',
          1001,
          'user01',
          'user01@test.com',
          '$2b$10$ocLiue.qK3S7vygj8IlCyuEGW6JQb0l8dAQ63BAbx795DY9N43NP.',
          '테스트유저1',
          'USER',
          'ACTIVE',
          'N'
      ),
      (
          1,
          'COMP001',
          1002,
          'user02',
          'user02@test.com',
          '$2b$10$ocLiue.qK3S7vygj8IlCyuEGW6JQb0l8dAQ63BAbx795DY9N43NP.',
          '테스트유저2',
          'USER',
          'ACTIVE',
          'N'
      ),
      (
          1,
          'COMP001',
          1003,
          'admin01',
          'admin01@test.com',
          '$2b$10$ocLiue.qK3S7vygj8IlCyuEGW6JQb0l8dAQ63BAbx795DY9N43NP.',
          '관리자',
          'ADMIN',
          'ACTIVE',
          'N'
      );